# Generated by Django 4.2.7 on 2023-11-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_treemenuitemmodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenuitemmodel',
            name='menu',
            field=models.ForeignKey(blank=True, default='main_menu', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tree.treemenumodel'),
        ),
    ]
