# Generated by Django 4.2.7 on 2023-11-17 13:43

from django.db import migrations, models
import django.db.models.deletion
import tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_alter_treemenuitemmodel_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenuitemmodel',
            name='menu',
            field=models.ForeignKey(blank=True, default=tree.models.get_default_menu, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tree.treemenumodel'),
        ),
    ]
