# Generated by Django 4.2.7 on 2023-11-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_alter_treemenuitemmodel_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treemenuitemmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='treemenumodel',
            name='slug',
        ),
    ]
