# Generated by Django 4.2.7 on 2023-11-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_remove_treemenuitemmodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemenuitemmodel',
            name='slug',
            field=models.CharField(default='slug_name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treemenumodel',
            name='slug',
            field=models.CharField(default='slug_menu', max_length=30, verbose_name='Menu slug'),
            preserve_default=False,
        ),
    ]
