# Generated by Django 4.2.7 on 2023-11-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_treemenuitemmodel_slug_treemenumodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenuitemmodel',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
        migrations.AlterField(
            model_name='treemenumodel',
            name='slug',
            field=models.SlugField(max_length=30, verbose_name='Menu slug'),
        ),
    ]
